### ISSUE TITLE
GET products By Id

### ISSUE THREAD

**Issue by Khorm247** [neuefische/hh-java-24-1-team-1#4]
**As a User** 
**I need** to search for products in my database
**to be able to** quickly find a specific product

#### Description
Implement a search feature that allows users to search for product based on criteria such as title or amount.

#### Acceptance Criteria

- [x] Create a GET "/api/products/{id}" endpoint to fetch the product specified by the id.
- [x] Display all informations given from the backend on a extra Route for each product "/products/:id
- [x] When clicking a product in the list view or navigating directly via the url the details page should be shown

#### Tasks

- [x] Implement a component that shows the product Details when you click on restaurant in the list view
- [x] Create a GET request to retrieve the product data from the backend (Get By Id).
- [x] Implement Unit and Integration Test.
- [x] add some styling
