### ISSUE TITLE
GET all products

### ISSUE THREAD

**Issue by MartinHermes86** [neuefische/hh-java-24-1-team-1#5]
**As a User** 
**I need** to view a list of all my products
**to be able to** have a comprehensive overview of my entire list.

## Description
Implement a feature that allows users to retrieve and view a list of all their products from the backend.

## Acceptance Criteria

- [x] Create a GET "/api/products" endpoint to fetch all products from the backend.
- [x] Display the list of all products on the starting page of the frontend.

## Tasks

(for developers team)

- [x] Create a Model with "Id, title and amount"
- [x] Create a "View All products" component in the UI.
- [x] Implement a GET request to retrieve all products from the backend.
- [x] Update the frontend to display the list of products.
- [x] Implement Unit and Integration Test.
- [x] add some styling
