### ISSUE TITLE
Add (POST) products

### ISSUE THREAD

**Issue by MaHambach** [neuefische/hh-java-24-1-team-1#6]
**As a User** 
**I need to** add a new products to my database
**to be able to** keep track of new products I acquire

## Description
Implement a feature that allows users to add a new product to their database. Users should be able to enter product details such as title and description.

## Acceptance Criteria

- [x] Create a POST endpoint "/api/products" to add a new restaurant to the backend.
- [x] The the Route "/products/add" should display the form, for the user to add a product.
- [x] Ensure that the added product appears in the list of products.

## Tasks

(for developers team)

- [x] Create a "Add product" button in the UI.
- [x] Implement a form to input product details.
- [x] Create a POST request to send product data to the backend.
- [x] Implement Unit and Integration Test.
- [x] add some styling
