### ISSUE TITLE
Edit (PUT) product

### ISSUE THREAD

**Issue by MaHambach** [neuefische/hh-java-24-1-team-1#7]
**As a User**
**I need** to edit the details of an existing product in my database
**to be able to** update information for a product
#### Description
Implement a feature that allows users to edit the details of a product in their . Users should be able to modify the title, amount and / or other information.

#### Acceptance Criteria

- [x] A "Edit"-Button is displayed on the details-page for each-product.
- [x] When the "Edit" button for a product is clicked, the user gets redirected to "/products/:id/edit
- [x] On the Edit-Page an edit form for that product should appear.
- [x] When submitting the form, then the product information should be updated in the backend and the user should be redirected to the details page.
- [x] Create an PUT Endpoint "/api/products/{id} to update the product.

#### Tasks

- [x] Add an "Edit" button for each product in the UI.
- [x] Implement an edit form to modify product details.
- [x] Create a PUT request to update product details on the backend.
- [x] Display updated information in the frontend after saving changes.
- [x] Implement Unit and Integration Test.
