### ISSUE TITLE
DELETE product

### ISSUE THREAD

**Issue by MaHambach** [neuefische/hh-java-24-1-team-1#8]
**As a User**
**I need** to delete a product from my database
**to be able to** remove product I no longer want in my collection.

#### Description
Implement a feature that allows users to delete a product from their database. Users should be able to remove a product they no longer wish to keep in their collection.

#### Acceptance Criteria

- [x] Create a DELETE Endpoint "/api/products/{id}" which deletes the product specified by the id.
- [x] On the Details-Page of each product should be a "delete" Button.
- [x] When clicking on the "Delete" button, the product should be removed from the database.

#### Tasks

- [x] Add a "Delete" button for each product in the UI.
- [x] Create a DELETE request or endpoint to remove the product from the backend.
- [x] Implement Unit and Integration Test.

**Comment by Khorm247** [comment]
das Delete übers Frontend funktioniert nicht bei mir?

hab auch extra ein neues produkt über das Frontend angelegt damit es eine passende ID hat
